// Registers all Solana Hardhat tasks. Kept separate from ./index, which holds helpers the tasks import.
import './base58'
import './createOFT'
import './createOFTAdapter'
import './debug'
import './getPrioFees'
import './getRateLimits'
import './initConfig'
import './retryMessage'
import './setAuthority'
import './setInboundRateLimit'
import './setOutboundRateLimit'
import './setUpdateAuthority'
import './updateMetadata'
import './endpoint/burn'
import './endpoint/clear'
import './endpoint/nilify'
import './endpoint/skip'
// Solana-aware overrides of the LayerZero wire / config tasks (lz:oapp:wire, lz:oapp:config:get, lz:ownable:transfer-ownership)
import '../common/config.get'
import '../common/wire'
